### ISSUE TITLE
Link referenced in video is not showing on page. 

### ISSUE THREAD

**Issue by smithWEBtek** [learn-co-curriculum/document-structure#1]
At about 7:48 into the video, he recommends a link that will be provided, regarding the best practice use of <meta charset="UTF-8”>. 

Link is not showing on the page, or in the remainder of the video.

**Comment by AnnJohn** [comment]
Thanks for raising this issue @smithpiano. We'll fix as soon as we can.

**Comment by jongrover** [comment]
Thanks @smithpiano resource link has been added below the video in commit 4a1b371
