### ISSUE TITLE
Report a bug line on profile

### ISSUE THREAD

**Issue by jonbf** [learn-co-curriculum/document-structure#3]
On Chrome, on a Mac, on the profile page, when I click "report a bug", nothing happens.

**Comment by aturkewi** [comment]
Hey @jonbf thanks for reporting this!

It looks like you're in our full stack web development program with Learn Expert support. We actually removed the "Report a Bug" button entirely. If you would like to report a bug with Learn, the best thing to do is to use the Ask A Question button. If the Learn Experts cannot solve the problem, then they will pass the bug along to our dev team :)

You can also raise issues with labs if there is something broken specifically with the lab (example: a gem was upgraded and now the tests won't run). 

Thanks for helping to report issues :)
